In [1]:
import numpy as np
import pandas as pd

In [3]:
df = pd.read_csv(r'C:\Users\Hp\Desktop\Python\Product Catalog Dataset\product_catalog.csv')
df.head()

,product_id,product_name,product_category,product_subcategory,brand,supplier,unit_price,product_cost,product_rating
0,PROD-000001,Apple Sharable bifurcated algorithm Smartphones,Electronics,Smartphones,Apple,Alibaba,686.90,474.06,4.3
1,PROD-000002,Google User-centric even-keeled encryption Sma...,Electronics,Smartphones,Google,Euro Logistics,978.26,519.66,2.9
2,PROD-000003,LG Face-to-face client-driven support Smartphones,Electronics,Smartphones,LG,Asian Manufacturing,275.51,185.48,3.9
3,PROD-000004,Sony Customer-focused systematic support Smart...,Electronics,Smartphones,Sony,Amazon Supply,1120.49,564.86,4.8
4,PROD-000005,OnePlus Quality-focused background parallelism...,Electronics,Smartphones,OnePlus,Direct Import,1282.18,695.54,2.9

In [11]:
df.loc[np.argsort(df['unit_price'].to_numpy())[-10:][::-1], ['product_name', 'unit_price']]

                                         product_name  unit_price
23  Asus Re-engineered content-based strategy Tablets     1482.95
11  LG Reverse-engineered even-keeled workforce Sm...     1433.55
50  HP Versatile actuating budgetary management Sm...     1380.75
64  Xiaomi Self-enabling exuding productivity Gami...     1370.54
76       OnePlus Switchable methodical neural-net TVs     1359.66
66        Samsung Distributed holistic task-force TVs     1353.21
61   OnePlus Adaptive uniform success Gaming Consoles     1340.54
73       Asus Configurable upward-trending matrix TVs     1303.99
55           HP Function-based neutral access Cameras     1285.89
4   OnePlus Quality-focused background parallelism...     1282.18

In [15]:
df['profit'] = df['unit_price'] - df['product_cost']
df.head()

,product_id,product_name,product_category,product_subcategory,brand,supplier,unit_price,product_cost,product_rating,profit
0,PROD-000001,Apple Sharable bifurcated algorithm Smartphones,Electronics,Smartphones,Apple,Alibaba,686.90,474.06,4.3,212.84
1,PROD-000002,Google User-centric even-keeled encryption Sma...,Electronics,Smartphones,Google,Euro Logistics,978.26,519.66,2.9,458.60
2,PROD-000003,LG Face-to-face client-driven support Smartphones,Electronics,Smartphones,LG,Asian Manufacturing,275.51,185.48,3.9,90.03
3,PROD-000004,Sony Customer-focused systematic support Smart...,Electronics,Smartphones,Sony,Amazon Supply,1120.49,564.86,4.8,555.63
4,PROD-000005,OnePlus Quality-focused background parallelism...,Electronics,Smartphones,OnePlus,Direct Import,1282.18,695.54,2.9,586.64

In [17]:
df.loc[np.argsort(df['profit'].to_numpy())[-10:][::-1],['product_name','unit_price','product_cost','profit']]

,product_name,unit_price,product_cost,profit
50,HP Versatile actuating budgetary management Sm...,1380.75,756.53,624.22
61,OnePlus Adaptive uniform success Gaming Consoles,1340.54,739.43,601.11
4,OnePlus Quality-focused background parallelism...,1282.18,695.54,586.64
995,Messika Networked disintermediate knowledge us...,968.68,402.49,566.19
55,HP Function-based neutral access Cameras,1285.89,725.44,560.45
3,Sony Customer-focused systematic support Smart...,1120.49,564.86,555.63
1002,Tous Diverse impactful software Chains,910.78,367.63,543.15
69,Apple Inverse mobile adapter TVs,1062.55,532.35,530.20
951,Mikimoto Monitored zero administration website...,922.33,397.10,525.23
971,Cartier Visionary background projection Earrings,968.50,452.57,515.93

In [31]:
price = df['unit_price'].to_numpy()
{'Mean': int(price.mean()),'Median': int(np.median(price)),'Minimum': int(price.min()),'Maximum': int(price.max()),'Standard Deviation': int(price.std())}

{'Mean': 245,
 'Median': 165,
 'Minimum': 6,
 'Maximum': 1482,
 'Standard Deviation': 251}

In [34]:
df.groupby('product_category')['unit_price'].mean().sort_values(ascending = False).head(10)

product_category
Electronics          798.844231
Jewelry              566.807391
Home Appliances      479.137949
Automotive           304.739630
Sports & Outdoors    261.443077
Home & Kitchen       236.689143
Baby & Kids          191.856533
Office Supplies      164.241000
Fashion              162.290000
Health & Wellness    158.633953
Name: unit_price, dtype: float64

In [38]:
df['margin_percentage'] = ((df['unit_price'] - df['product_cost']) / df['unit_price']) * 100
df.groupby('product_name')['margin_percentage'].sum().sort_values(ascending = False).head(10)

product_name
Unilever Stand-alone static implementation Produce                     74.927536
P&G Synchronized next generation data-warehouse Organic                74.741913
Kellogg's Operative incremental collaboration Frozen Foods             74.497682
Unilever Switchable intangible pricing structure Meat                  73.400745
Kraft Heinz Persistent systematic success Dairy                        73.285662
Coca-Cola Balanced asynchronous core Organic                           73.278546
Coca-Cola Distributed composite Graphic Interface Beverages            73.111292
General Mills Decentralized context-sensitive monitoring Dairy         72.968659
Kraft Heinz Programmable leadingedge budgetary management Beverages    72.683514
P&G Quality-focused analyzing architecture Snacks                      72.678069
Name: margin_percentage, dtype: float64

In [41]:
def above_avg(unit_price):
    return (unit_price > unit_price.mean()).sum()

int(above_avg(df['unit_price']))

400

In [42]:
df.groupby('brand')['profit'].sum().sort_values(ascending = False).head(10)

brand
Samsung         4317.20
LG              3825.17
David Yurman    3204.63
OnePlus         3139.43
Whirlpool       2932.98
HP              2913.27
Asus            2830.45
Pandora         2684.06
Dyson           2558.77
Mikimoto        2257.99
Name: profit, dtype: float64

In [47]:
rating = df['product_rating'].to_numpy()
price = df['unit_price'].to_numpy()

np.corrcoef(rating, price)[0, 1]

np.float64(-0.020239344130239402)

In [49]:
df.groupby('supplier')['profit'].mean().sort_values(ascending=False)

supplier
Amazon Supply            128.865952
Domestic Producers       128.307581
Euro Logistics           128.273750
Direct Import            123.143115
Pacific Trade            119.552075
MultiSource              117.349860
North American Supply    113.449767
Asian Manufacturing      111.537115
Alibaba                  107.280947
Global Trade             107.233208
Name: profit, dtype: float64

In [51]:
df.groupby('supplier')['profit'].mean().sort_values(ascending=False)

supplier
Amazon Supply            128.865952
Domestic Producers       128.307581
Euro Logistics           128.273750
Direct Import            123.143115
Pacific Trade            119.552075
MultiSource              117.349860
North American Supply    113.449767
Asian Manufacturing      111.537115
Alibaba                  107.280947
Global Trade             107.233208
Name: profit, dtype: float64